trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: SyncStage
    jobs:
      - job: sync
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            persistCredentials: true
            clean: true
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                docker build -t sync-repo:latest .
                docker run -t \
                  --env REPO_ORIGIN="$REPO_ORIGIN" \
                  --env REPO_DESTIN="$REPO_DESTIN" \
                  --env REPO_ORIGIN_TOKEN="$(REPO_ORIGIN_TOKEN)" \
                  --env REPO_DESTIN_TOKEN="$(REPO_DESTIN_TOKEN)" \
                sync-repo:latest

